# Generated by Django 2.2.16 on 2022-05-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamdb', '0003_auto_20220513_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={},
        ),
    ]
